spring:
  application:
    name: SpringBootRedis-PubSub-Subsrciber-A
#Redis config details
  data:
    redis:
      host: localhost
      port: 6379
#Springboot application server port
server:
  port: 9091

