#Application name
spring:
  application:
    name: SpringBootRabbitMQ-Consumer
#RabbitMQ config details
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#Rabbitmq additional config
rabbitmq:
  wish:
    queue:
      name: wish-queue
  score:
    queue:
      name: score-queue
#Springboot application server port number
server:
  port: 9092
