#Application name
spring:
  application:
    name: SpringBootRabbitMQ-Producer
#RabbitMQ config details
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#Rabbitmq additional config
rabbitmq:
  wish:
    queue:
      name: wish-queue
    routing:
      key: wish-routing-key
  score:
    queue:
      name: score-queue
    routing:
      key: score-routing-key
  exchange: my-exchange
#Springboot application server port number
server:
  port: 9090
