#Spring application Name
spring:
  application:
    name: SpringBootActiveMQ-Consumer
#ActiveMQ configuration
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    packages:
      trust-all: true
#ActiveMQ additional config
activemq:
  queue:
    name: student-queue
  topic:
    name: student-topic
server:
  port: 9092

